In [1]:
import pytest

from uf3.jax.potentials import uf3_interaction, uf2_interaction
import jax.numpy as jnp
import numpy as onp
import ndsplines
from numpy.testing import assert_allclose
from functools import partial

from uf3.jax.jax_splines import bspline_factors, BSplineBackend, _ndSpline_unsafe
from uf3.util.random import random_spline

from jax_md import space
from jax import vmap, grad

from jax.config import config
config.update("jax_enable_x64", True)
# from utils import make_random_spline

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [2]:
c, k, x = random_spline((10,10), min=(0.0,10), max=(9.0,19), sample=5)

In [3]:
x

DeviceArray([[ 7.39099787, 10.56934017],
             [ 6.159997  , 15.88732734],
             [ 0.41427631, 17.29606005],
             [ 7.63080072, 17.34434256],
             [ 8.91813633, 18.22223921]], dtype=float64)

In [4]:
s = _ndSpline_unsafe(c, k, (3,3))

In [5]:
s(x[0])

DeviceArray(-0.0079834, dtype=float64)

In [6]:
vmap(s)(x)

DeviceArray([-7.98339755e-03, -5.10440679e+00, -2.96282701e-03,
             -5.95357329e-01, -1.40475968e-05], dtype=float64)

In [7]:
sp = ndsplines.NDSpline(k, c, (3,3))

In [9]:
sp(x)

array([-7.98339755e-03, -5.10440679e+00, -2.96282701e-03, -5.95357329e-01,
       -1.40475968e-05])